name: Create Plugin ZIP on Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Build the plugin zip
      run: |
        mkdir abcdo-wc-navex
        cp -r ./* abcdo-wc-navex/
        rm -rf abcdo-wc-navex/.git
        rm -rf abcdo-wc-navex/.github
        zip -r abcdo-wc-navex.zip abcdo-wc-navex
        
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "abcdo-wc-navex.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true