name: Build and Release Plugin ZIP

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract plugin version
      id: get_version
      run: |
        PLUGIN_VERSION=$(grep -oP "Version:\s*\K[0-9.]+" abcdo-wc-navex.php)
        echo "version=$PLUGIN_VERSION" >> $GITHUB_OUTPUT

    - name: Build the plugin zip
      id: build_zip
      run: |
        PLUGIN_SLUG="abcdo-wc-navex"
        VERSION=${{ steps.get_version.outputs.version }}
        ZIP_FILE="${PLUGIN_SLUG}.zip" # Simplified name for consistency
        
        # Create a ZIP archive from the current commit, respecting .distignore
        git archive -o "${ZIP_FILE}" --prefix="${PLUGIN_SLUG}/" HEAD
        
        echo "zip_path=${ZIP_FILE}" >> $GITHUB_OUTPUT
        echo "zip_name=${ZIP_FILE}" >> $GITHUB_OUTPUT

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./${{ steps.build_zip.outputs.zip_path }}
        asset_name: ${{ steps.build_zip.outputs.zip_name }}
        asset_content_type: application/zip
