name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Zip Archive
        run: zip -r abcdo-wc-navex.zip . -x "*.git*" "*node_modules*" "*.vscode*" "*.idea*" "*README.md*"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: abcdo-wc-navex.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
