name: Build, Tag & Release

on:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Plugin Version
        id: get_version
        run: |
          PLUGIN_VERSION=$(grep -oP "Version:\s*\K[0-9.]+" abcdo-wc-navex.php)
          echo "version=${PLUGIN_VERSION}" >> $GITHUB_OUTPUT
        
      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.get_version.outputs.version }}
          name: Release ${{ steps.get_version.outputs.version }}
          body: "Automated release for version ${{ steps.get_version.outputs.version }}"
          artifacts: "${{ steps.deploy.outputs.zip-path }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          prerelease: false
